project:
  type: website
  output-dir: docs

website:
  title: "alphasignal533"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
    right:
      - icon: github
        href: https://github.com/im-Tree/Fintech533-website

format:
  html:
    theme:
      - litera
      - sandstone
    css: styles.css
    toc: true



